/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng nhập
         * @description Trả về access token JWT ngắn hạn và refresh token mờ. Sai email và sai
         *     mật khẩu cho cùng một lỗi để không lộ email nào đang tồn tại.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tạo tài khoản học viên
         * @description Tạo tài khoản rồi đăng nhập luôn: trả về đúng cặp token như /auth/login.
         *     Vai trò luôn là `student`; không có cách nào tự nhận quyền admin.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng nhập bằng Google
         * @description Đổi authorization code của Google lấy phiên Lingora. `redirect_uri` phải
         *     khớp với cái đã dùng lúc chuyển hướng sang Google.
         *
         *     Tài khoản Google đã gắn thì đăng nhập thẳng; chưa gắn mà email đã có
         *     tài khoản Lingora thì được gắn vào tài khoản đó; chưa có gì thì tạo mới
         *     với vai trò `student`. Email chưa được Google xác minh bị từ chối.
         *
         *     Trả 503 khi máy chủ chưa được cấu hình GOOGLE_CLIENT_ID và
         *     GOOGLE_CLIENT_SECRET.
         */
        post: operations["signInWithGoogle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Làm mới phiên
         * @description Xoay vòng token: refresh token gửi lên bị thu hồi ngay khi cặp mới được
         *     cấp, nên mỗi refresh token chỉ dùng được đúng một lần.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng xuất
         * @description Thu hồi refresh token. Gọi nhiều lần vẫn thành công.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thông tin tài khoản đang đăng nhập */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liệt kê khoá học
         * @description Phân trang keyset. Trang đầu không truyền `cursor`; các trang sau truyền
         *     lại nguyên văn `next_cursor` của trang trước. `next_cursor` bằng `null`
         *     nghĩa là đã hết dữ liệu.
         */
        get: operations["listCourses"];
        put?: never;
        /** Tạo khoá học */
        post: operations["createCourse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Sắp xếp khoá học trong một bậc
         * @description `course_ids` phải là đúng tập khoá hiện có của bậc đó. Thiếu, thừa hay
         *     trùng đều bị từ chối, vì một lần sắp xếp thiếu khoá sẽ để lại những khoá
         *     mang thứ tự cũ lẫn vào giữa.
         */
        put: operations["reorderCourses"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        /**
         * Lấy khoá học theo id
         * @description Khoá `draft` chỉ admin đọc được; người khác nhận 404 chứ không phải 403,
         *     vì 403 đã xác nhận bản ghi đó tồn tại.
         */
        get: operations["getCourse"];
        put?: never;
        post?: never;
        /** Xoá mềm khoá học */
        delete: operations["deleteCourse"];
        options?: never;
        head?: never;
        /**
         * Cập nhật một phần khoá học
         * @description Field vắng mặt thì giữ nguyên. Riêng `cover_image_url` gửi `null` nghĩa
         *     là xoá ảnh bìa. Body rỗng bị từ chối.
         */
        patch: operations["updateCourse"];
        trace?: never;
    };
    "/courses/by-slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lấy khoá học theo slug
         * @description Khoá `draft` chỉ admin đọc được; người khác nhận 404 chứ không phải 403,
         *     vì 403 đã xác nhận bản ghi đó tồn tại.
         */
        get: operations["getCourseBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        /**
         * Liệt kê bài học của một khoá
         * @description Sắp xếp theo `position` tăng dần. Khoá không tồn tại trả về 404; khoá có
         *     thật nhưng chưa có bài trả về mảng rỗng.
         *
         *     Bài không có trạng thái riêng, nó thừa hưởng của khoá: bài thuộc khoá
         *     `draft` chỉ admin đọc được, người khác cũng nhận 404.
         */
        get: operations["listCourseLessons"];
        put?: never;
        /**
         * Thêm bài học vào khoá
         * @description Bài mới luôn đứng cuối; đổi thứ tự bằng endpoint order.
         */
        post: operations["createLesson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}/lessons/order": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Sắp xếp lại bài học trong khoá
         * @description Danh sách phải liệt kê đúng tập bài hiện có của khoá — thiếu, thừa hay
         *     trùng đều bị từ chối. Vị trí mới lấy từ chính thứ tự của mảng.
         */
        put: operations["reorderLessons"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{lessonId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lessonId: string;
            };
            cookie?: never;
        };
        /**
         * Lấy bài học theo id
         * @description Bài không có trạng thái riêng, nó thừa hưởng của khoá: bài thuộc khoá
         *     `draft` chỉ admin đọc được, người khác nhận 404.
         */
        get: operations["getLesson"];
        put?: never;
        post?: never;
        /** Xoá mềm bài học */
        delete: operations["deleteLesson"];
        options?: never;
        head?: never;
        /**
         * Cập nhật một phần bài học
         * @description position không sửa được ở đây; dùng endpoint order của khoá.
         */
        patch: operations["updateLesson"];
        trace?: never;
    };
    "/me/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Đọc toàn bộ tiến độ của người đang đăng nhập
         * @description Trả một lần đủ dữ liệu để dựng mọi màn: tỉ lệ từng khoá, danh sách bài
         *     đã đánh dấu xong, và khoá được học gần đây nhất.
         */
        get: operations["getProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/progress/lessons/{lessonId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lessonId: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Đánh dấu đã học xong một bài
         * @description Idempotent: gọi lại không dời mốc hoàn thành đã ghi lần đầu.
         */
        put: operations["markLessonComplete"];
        post?: never;
        /**
         * Gỡ đánh dấu hoàn thành
         * @description Idempotent: gỡ một bài chưa từng đánh dấu vẫn trả 204.
         */
        delete: operations["markLessonIncomplete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocabulary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Danh sách từ vựng của một bài
         * @description Công cụ soạn nội dung, chỉ admin. Người học đọc từ của mình ở
         *     `/me/vocabulary`, nơi hàng đợi được lọc theo bài họ đã học xong.
         */
        get: operations["listVocabulary"];
        put?: never;
        /** Thêm một từ vào bài */
        post: operations["createVocabularyEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocabulary/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Xoá mềm một từ */
        delete: operations["deleteVocabularyEntry"];
        options?: never;
        head?: never;
        /** Cập nhật một phần của từ */
        patch: operations["updateVocabularyEntry"];
        trace?: never;
    };
    "/me/vocabulary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Từ vựng đã mở khoá của người đang đăng nhập
         * @description Chỉ gồm từ thuộc những bài người này đã đánh dấu hoàn thành. Chưa ôn lần
         *     nào thì `review` là `null` và `state` là `due`.
         */
        get: operations["listMyVocabulary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/vocabulary/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bốn ô thống kê của màn Từ vựng */
        get: operations["getVocabularyStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/vocabulary/{entryId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ghi nhận một lần ôn
         * @description Tính lịch tiếp theo theo SM-2. Từ thuộc bài chưa hoàn thành bị từ chối
         *     với 403.
         */
        post: operations["reviewVocabularyEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        UserRole: "admin" | "student";
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            role: components["schemas"]["UserRole"];
            /** Format: date-time */
            created_at: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /**
             * Format: password
             * @description Tối thiểu 12 ký tự.
             */
            password: string;
            display_name: string;
        };
        GoogleSignInRequest: {
            /** @description Authorization code Google trả về. */
            code: string;
            /** @description Đúng redirect_uri đã dùng ở bước chuyển hướng. */
            redirect_uri: string;
        };
        /**
         * @description `due` đến hạn ôn (kể cả từ chưa ôn lần nào), `learning` đang học,
         *     `mastered` khoảng cách ôn đã từ 21 ngày trở lên.
         * @enum {string}
         */
        VocabularyState: "due" | "learning" | "mastered";
        VocabularyEntry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            lesson_id: string;
            word: string;
            ipa: string;
            meaning: string;
            example: string;
            example_vi: string;
            /** Format: int32 */
            position: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        VocabularyEntryCreate: {
            /** Format: uuid */
            lesson_id: string;
            word: string;
            ipa?: string;
            meaning: string;
            example?: string;
            example_vi?: string;
        };
        VocabularyEntryUpdate: {
            word?: string;
            ipa?: string;
            meaning?: string;
            example?: string;
            example_vi?: string;
        };
        VocabularyEntryList: {
            items: components["schemas"]["VocabularyEntry"][];
        };
        VocabularyReview: {
            /** Format: double */
            ease_factor: number;
            /** Format: int32 */
            interval_days: number;
            /** Format: int32 */
            repetitions: number;
            /** Format: date */
            due_on: string;
            /** Format: date-time */
            last_reviewed_at: string;
        };
        VocabularyCard: {
            entry: components["schemas"]["VocabularyEntry"];
            level: components["schemas"]["CourseLevel"];
            state: components["schemas"]["VocabularyState"];
            /**
             * Format: int32
             * @description Số đốt sáng trên vạch 5 đốt.
             */
            familiarity: number;
            /** @description `null` khi người học chưa ôn từ này lần nào. */
            review: components["schemas"]["VocabularyReview"] | null;
        };
        VocabularyCardList: {
            items: components["schemas"]["VocabularyCard"][];
        };
        VocabularyStats: {
            /** Format: int64 */
            learned: number;
            /** Format: int64 */
            due_today: number;
            /** Format: int64 */
            mastered: number;
            /** Format: int64 */
            new_this_week: number;
        };
        VocabularyReviewRequest: {
            /** @enum {string} */
            grade: "remembered" | "forgot";
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        TokenPair: {
            /** @description JWT HS256 dùng cho header Authorization. */
            access_token: string;
            /** @description Chuỗi mờ, chỉ dùng được một lần. */
            refresh_token: string;
            /**
             * Format: int64
             * @description Số giây còn hiệu lực của access token.
             */
            expires_in: number;
            user: components["schemas"]["User"];
        };
        /**
         * @description Trình độ theo khung CEFR.
         * @enum {string}
         */
        CourseLevel: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
        /**
         * @description Trạng thái xuất bản.
         * @enum {string}
         */
        CourseStatus: "draft" | "published";
        Course: {
            /** Format: uuid */
            id: string;
            /** @example ngu-phap-co-ban */
            slug: string;
            /** @example Ngữ pháp cơ bản */
            title: string;
            description: string;
            level: components["schemas"]["CourseLevel"];
            status: components["schemas"]["CourseStatus"];
            /** Format: uri */
            cover_image_url: string | null;
            /**
             * Format: int32
             * @description Thứ tự trong bậc, do người soạn đặt.
             */
            position: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CourseList: {
            items: components["schemas"]["Course"][];
            /** @description Con trỏ cho trang kế tiếp; `null` nghĩa là đã hết. */
            next_cursor: string | null;
        };
        CourseCreate: {
            slug: string;
            title: string;
            description?: string;
            level: components["schemas"]["CourseLevel"];
            status?: components["schemas"]["CourseStatus"];
            /** Format: uri */
            cover_image_url?: string | null;
        };
        CourseOrder: {
            level: components["schemas"]["CourseLevel"];
            /** @description Toàn bộ id khoá của bậc đó, theo thứ tự mong muốn. */
            course_ids: string[];
        };
        CourseUpdate: {
            slug?: string;
            title?: string;
            description?: string;
            level?: components["schemas"]["CourseLevel"];
            status?: components["schemas"]["CourseStatus"];
            /** Format: uri */
            cover_image_url?: string | null;
        };
        Lesson: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            course_id: string;
            slug: string;
            title: string;
            /** Format: int32 */
            position: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        LessonCreate: {
            slug: string;
            title: string;
        };
        LessonUpdate: {
            slug?: string;
            title?: string;
        };
        LessonOrder: {
            /** @description Toàn bộ id bài của khoá, theo thứ tự mong muốn. */
            lesson_ids: string[];
        };
        LessonList: {
            items: components["schemas"]["Lesson"][];
        };
        Error: {
            /** @enum {string} */
            code: "validation_error" | "malformed_body" | "unauthorized" | "forbidden" | "not_found" | "method_not_allowed" | "conflict" | "rate_limited" | "internal_error";
            /** @description Câu thông báo tiếng Việt, hiển thị được cho người dùng. */
            message: string;
            /** @description Lỗi theo từng field, chỉ có với validation_error. */
            details?: {
                [key: string]: string;
            };
        };
        CourseProgress: {
            /** Format: uuid */
            course_id: string;
            /**
             * Format: int64
             * @description Tổng số bài chưa xoá của khoá — mẫu số của tỉ lệ.
             */
            lesson_count: number;
            /** Format: int64 */
            completed_count: number;
        };
        DayActivity: {
            /** Format: date */
            date: string;
            /** Format: int64 */
            completed_lessons: number;
        };
        ProgressSnapshot: {
            courses: components["schemas"]["CourseProgress"][];
            /** @description Id các bài đã đánh dấu xong, mới nhất trước. */
            completed_lesson_ids: string[];
            /**
             * Format: uuid
             * @description Khoá được học gần đây nhất; `null` khi chưa học bài nào.
             */
            latest_course_id: string | null;
            /**
             * Format: int64
             * @description XP đã đạt hôm nay, tính theo giờ Việt Nam.
             */
            today_xp: number;
            /**
             * Format: int64
             * @description Mục tiêu XP mỗi ngày.
             */
            goal_xp: number;
            /**
             * Format: int64
             * @description XP cho mỗi bài hoàn thành. Có mặt để phía trước cộng trừ được ngay
             *     khi người học bấm, mà không phải viết cứng lại con số của server.
             */
            xp_per_lesson: number;
            /**
             * Format: int64
             * @description Số ngày học liên tiếp. Vẫn giữ nguyên khi hôm nay chưa học nhưng
             *     hôm qua có — người học còn nguyên hôm nay để nối tiếp.
             */
            streak_days: number;
            /** @description Bảy ngày gần nhất, cũ trước mới sau; ngày không học vẫn có mặt. */
            week: components["schemas"]["DayActivity"][];
        };
    };
    responses: {
        /** @description Thử quá nhiều lần; header Retry-After cho biết phải chờ bao lâu. */
        TooManyRequests: {
            headers: {
                /** @description Số giây còn phải chờ. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Dữ liệu vào không hợp lệ */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Thiếu token hoặc token không hợp lệ */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Token hợp lệ nhưng không đủ quyền */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Không tìm thấy */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Xung đột với dữ liệu đang có */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        CourseId: string;
        /**
         * @description Chỉ có tác dụng với token admin. Người gọi khác luôn nhận `published`,
         *     và nếu xin `draft` thì nhận một trang rỗng.
         */
        StatusFilter: components["schemas"]["CourseStatus"];
        LevelFilter: components["schemas"]["CourseLevel"];
        /** @description Mặc định 20, trần 100. */
        PageSize: number;
        /** @description Chuỗi mờ lấy từ `next_cursor` của trang trước. */
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Cặp token mới */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Tài khoản mới kèm cặp token */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    signInWithGoogle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleSignInRequest"];
            };
        };
        responses: {
            /** @description Phiên đăng nhập */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            /** @description Đăng nhập Google chưa được bật trên máy chủ */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Cặp token mới */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Đã đăng xuất */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tài khoản đang đăng nhập */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listCourses: {
        parameters: {
            query?: {
                /**
                 * @description Chỉ có tác dụng với token admin. Người gọi khác luôn nhận `published`,
                 *     và nếu xin `draft` thì nhận một trang rỗng.
                 */
                status?: components["parameters"]["StatusFilter"];
                level?: components["parameters"]["LevelFilter"];
                /** @description Mặc định 20, trần 100. */
                page_size?: components["parameters"]["PageSize"];
                /** @description Chuỗi mờ lấy từ `next_cursor` của trang trước. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Một trang khoá học */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseList"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createCourse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseCreate"];
            };
        };
        responses: {
            /** @description Khoá học đã được tạo */
            201: {
                headers: {
                    /** @description Đường dẫn tới khoá học vừa tạo */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    reorderCourses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseOrder"];
            };
        };
        responses: {
            /** @description Đã sắp xếp */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Khoá học */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Đã xoá */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseUpdate"];
            };
        };
        responses: {
            /** @description Khoá học sau khi cập nhật */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getCourseBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Khoá học */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listCourseLessons: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Danh sách bài học */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonList"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    createLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonCreate"];
            };
        };
        responses: {
            /** @description Bài học đã được tạo */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    reorderLessons: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonOrder"];
            };
        };
        responses: {
            /** @description Đã sắp xếp lại */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lessonId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bài học */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lessonId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Đã xoá */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lessonId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonUpdate"];
            };
        };
        responses: {
            /** @description Bài học sau khi cập nhật */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tiến độ hiện tại */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressSnapshot"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    markLessonComplete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lessonId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Đã ghi nhận */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    markLessonIncomplete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lessonId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Đã gỡ */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listVocabulary: {
        parameters: {
            query: {
                lesson_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Từ của bài, theo thứ tự position */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyEntryList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createVocabularyEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VocabularyEntryCreate"];
            };
        };
        responses: {
            /** @description Từ vừa thêm */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyEntry"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteVocabularyEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Đã xoá */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateVocabularyEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VocabularyEntryUpdate"];
            };
        };
        responses: {
            /** @description Từ sau khi cập nhật */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyEntry"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listMyVocabulary: {
        parameters: {
            query?: {
                state?: components["schemas"]["VocabularyState"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Danh sách thẻ từ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyCardList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getVocabularyStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thống kê */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyStats"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    reviewVocabularyEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VocabularyReviewRequest"];
            };
        };
        responses: {
            /** @description Lịch ôn sau lần này */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyReview"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
